services:
  - type: web
    name: sentinel
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
