services:
  - type: web
    name: sentinel
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
