# render.yaml — Sentinel Orchestrator Deployment (Phase 2.1)
# ----------------------------------------------------------
# Streamlit + OpenAI app for Longbow Capital.
# Includes OCR system packages, extended health check, and environment variables.

services:
  - type: web
    name: sentinal-orchestrator
    env: python
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false              # Add manually in Render dashboard
      - key: OPENAI_MODEL
        value: gpt-4o
    healthCheckPath: /
    healthCheckTimeout: 180      # allows longer startup time (3 minutes)
    autoDeploy: true
    disk:
      name: sentinal-cache
      mountPath: /data
      sizeGB: 1
